export const apiData = [
  {
    code: "af",
    name: "Afrikaans",
    nativeName: "Afrikaans",
    dir: "ltr",
  },
  {
    code: "am",
    name: "Amharic",
    nativeName: "አማርኛ",
    dir: "ltr",
  },
  {
    code: "ar",
    name: "Arabic",
    nativeName: "العربية",
    dir: "rtl",
  },
  {
    code: "as",
    name: "Assamese",
    nativeName: "অসমীয়া",
    dir: "ltr",
  },
  {
    code: "az",
    name: "Azerbaijani",
    nativeName: "Azərbaycan",
    dir: "ltr",
  },
  {
    code: "ba",
    name: "Bashkir",
    nativeName: "Bashkir",
    dir: "ltr",
  },
  {
    code: "bg",
    name: "Bulgarian",
    nativeName: "Български",
    dir: "ltr",
  },
  {
    code: "bn",
    name: "Bangla",
    nativeName: "বাংলা",
    dir: "ltr",
  },
  {
    code: "bo",
    name: "Tibetan",
    nativeName: "བོད་སྐད་",
    dir: "ltr",
  },
  {
    code: "bs",
    name: "Bosnian",
    nativeName: "Bosnian",
    dir: "ltr",
  },
  {
    code: "ca",
    name: "Catalan",
    nativeName: "Català",
    dir: "ltr",
  },
  {
    code: "cs",
    name: "Czech",
    nativeName: "Čeština",
    dir: "ltr",
  },
  {
    code: "cy",
    name: "Welsh",
    nativeName: "Cymraeg",
    dir: "ltr",
  },
  {
    code: "da",
    name: "Danish",
    nativeName: "Dansk",
    dir: "ltr",
  },
  {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
    dir: "ltr",
  },
  {
    code: "dsb",
    name: "Lower Sorbian",
    nativeName: "Dolnoserbšćina",
    dir: "ltr",
  },
  {
    code: "dv",
    name: "Divehi",
    nativeName: "ދިވެހިބަސް",
    dir: "rtl",
  },
  {
    code: "el",
    name: "Greek",
    nativeName: "Ελληνικά",
    dir: "ltr",
  },
  {
    code: "en",
    name: "English",
    nativeName: "English",
    dir: "ltr",
  },
  {
    code: "es",
    name: "Spanish",
    nativeName: "Español",
    dir: "ltr",
  },
  {
    code: "et",
    name: "Estonian",
    nativeName: "Eesti",
    dir: "ltr",
  },
  {
    code: "eu",
    name: "Basque",
    nativeName: "Euskara",
    dir: "ltr",
  },
  {
    code: "fa",
    name: "Persian",
    nativeName: "فارسی",
    dir: "rtl",
  },
  {
    code: "fi",
    name: "Finnish",
    nativeName: "Suomi",
    dir: "ltr",
  },
  {
    code: "fil",
    name: "Filipino",
    nativeName: "Filipino",
    dir: "ltr",
  },
  {
    code: "fj",
    name: "Fijian",
    nativeName: "Na Vosa Vakaviti",
    dir: "ltr",
  },
  {
    code: "fo",
    name: "Faroese",
    nativeName: "Føroyskt",
    dir: "ltr",
  },
  {
    code: "fr",
    name: "French",
    nativeName: "Français",
    dir: "ltr",
  },
  {
    code: "fr-CA",
    name: "French (Canada)",
    nativeName: "Français (Canada)",
    dir: "ltr",
  },
  {
    code: "ga",
    name: "Irish",
    nativeName: "Gaeilge",
    dir: "ltr",
  },
  {
    code: "gl",
    name: "Galician",
    nativeName: "Galego",
    dir: "ltr",
  },
  {
    code: "gom",
    name: "Konkani",
    nativeName: "Konkani",
    dir: "ltr",
  },
  {
    code: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
    dir: "ltr",
  },
  {
    code: "ha",
    name: "Hausa",
    nativeName: "Hausa",
    dir: "ltr",
  },
  {
    code: "he",
    name: "Hebrew",
    nativeName: "עברית",
    dir: "rtl",
  },
  {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    dir: "ltr",
  },
  {
    code: "hr",
    name: "Croatian",
    nativeName: "Hrvatski",
    dir: "ltr",
  },
  {
    code: "hsb",
    name: "Upper Sorbian",
    nativeName: "Hornjoserbšćina",
    dir: "ltr",
  },
  {
    code: "ht",
    name: "Haitian Creole",
    nativeName: "Haitian Creole",
    dir: "ltr",
  },
  {
    code: "hu",
    name: "Hungarian",
    nativeName: "Magyar",
    dir: "ltr",
  },
  {
    code: "hy",
    name: "Armenian",
    nativeName: "Հայերեն",
    dir: "ltr",
  },
  {
    code: "id",
    name: "Indonesian",
    nativeName: "Indonesia",
    dir: "ltr",
  },
  {
    code: "ig",
    name: "Igbo",
    nativeName: "Ásụ̀sụ́ Ìgbò",
    dir: "ltr",
  },
  {
    code: "ikt",
    name: "Inuinnaqtun",
    nativeName: "Inuinnaqtun",
    dir: "ltr",
  },
  {
    code: "is",
    name: "Icelandic",
    nativeName: "Íslenska",
    dir: "ltr",
  },
  {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
    dir: "ltr",
  },
  {
    code: "iu",
    name: "Inuktitut",
    nativeName: "ᐃᓄᒃᑎᑐᑦ",
    dir: "ltr",
  },
  {
    code: "iu-Latn",
    name: "Inuktitut (Latin)",
    nativeName: "Inuktitut (Latin)",
    dir: "ltr",
  },
  {
    code: "ja",
    name: "Japanese",
    nativeName: "日本語",
    dir: "ltr",
  },
  {
    code: "ka",
    name: "Georgian",
    nativeName: "ქართული",
    dir: "ltr",
  },
  {
    code: "kk",
    name: "Kazakh",
    nativeName: "Қазақ Тілі",
    dir: "ltr",
  },
  {
    code: "km",
    name: "Khmer",
    nativeName: "ខ្មែរ",
    dir: "ltr",
  },
  {
    code: "kmr",
    name: "Kurdish (Northern)",
    nativeName: "Kurdî (Bakur)",
    dir: "ltr",
  },
  {
    code: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
    dir: "ltr",
  },
  {
    code: "ko",
    name: "Korean",
    nativeName: "한국어",
    dir: "ltr",
  },
  {
    code: "ku",
    name: "Kurdish (Central)",
    nativeName: "Kurdî (Navîn)",
    dir: "rtl",
  },
  {
    code: "ky",
    name: "Kyrgyz",
    nativeName: "Кыргызча",
    dir: "ltr",
  },
  {
    code: "ln",
    name: "Lingala",
    nativeName: "Lingála",
    dir: "ltr",
  },
  {
    code: "lo",
    name: "Lao",
    nativeName: "ລາວ",
    dir: "ltr",
  },
  {
    code: "lt",
    name: "Lithuanian",
    nativeName: "Lietuvių",
    dir: "ltr",
  },
  {
    code: "lug",
    name: "Ganda",
    nativeName: "Ganda",
    dir: "ltr",
  },
  {
    code: "lv",
    name: "Latvian",
    nativeName: "Latviešu",
    dir: "ltr",
  },
  {
    code: "lzh",
    name: "Chinese (Literary)",
    nativeName: "中文 (文言文)",
    dir: "ltr",
  },
  {
    code: "mai",
    name: "Maithili",
    nativeName: "Maithili",
    dir: "ltr",
  },
  {
    code: "mg",
    name: "Malagasy",
    nativeName: "Malagasy",
    dir: "ltr",
  },
  {
    code: "mi",
    name: "Māori",
    nativeName: "Te Reo Māori",
    dir: "ltr",
  },
  {
    code: "mk",
    name: "Macedonian",
    nativeName: "Македонски",
    dir: "ltr",
  },
  {
    code: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
    dir: "ltr",
  },
  {
    code: "mn-Cyrl",
    name: "Mongolian (Cyrillic)",
    nativeName: "Mongolian (Cyrillic)",
    dir: "ltr",
  },
  {
    code: "mn-Mong",
    name: "Mongolian (Traditional)",
    nativeName: "ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ",
    dir: "ltr",
  },
  {
    code: "mr",
    name: "Marathi",
    nativeName: "मराठी",
    dir: "ltr",
  },
  {
    code: "ms",
    name: "Malay",
    nativeName: "Melayu",
    dir: "ltr",
  },
  {
    code: "mt",
    name: "Maltese",
    nativeName: "Malti",
    dir: "ltr",
  },
  {
    code: "mww",
    name: "Hmong Daw",
    nativeName: "Hmong Daw",
    dir: "ltr",
  },
  {
    code: "my",
    name: "Myanmar (Burmese)",
    nativeName: "မြန်မာ",
    dir: "ltr",
  },
  {
    code: "nb",
    name: "Norwegian",
    nativeName: "Norsk Bokmål",
    dir: "ltr",
  },
  {
    code: "ne",
    name: "Nepali",
    nativeName: "नेपाली",
    dir: "ltr",
  },
  {
    code: "nl",
    name: "Dutch",
    nativeName: "Nederlands",
    dir: "ltr",
  },
  {
    code: "nso",
    name: "Sesotho sa Leboa",
    nativeName: "Sesotho sa Leboa",
    dir: "ltr",
  },
  {
    code: "nya",
    name: "Nyanja",
    nativeName: "Nyanja",
    dir: "ltr",
  },
  {
    code: "or",
    name: "Odia",
    nativeName: "ଓଡ଼ିଆ",
    dir: "ltr",
  },
  {
    code: "otq",
    name: "Querétaro Otomi",
    nativeName: "Hñähñu",
    dir: "ltr",
  },
  {
    code: "pa",
    name: "Punjabi",
    nativeName: "ਪੰਜਾਬੀ",
    dir: "ltr",
  },
  {
    code: "pl",
    name: "Polish",
    nativeName: "Polski",
    dir: "ltr",
  },
  {
    code: "prs",
    name: "Dari",
    nativeName: "دری",
    dir: "rtl",
  },
  {
    code: "ps",
    name: "Pashto",
    nativeName: "پښتو",
    dir: "rtl",
  },
  {
    code: "pt",
    name: "Portuguese (Brazil)",
    nativeName: "Português (Brasil)",
    dir: "ltr",
  },
  {
    code: "pt-PT",
    name: "Portuguese (Portugal)",
    nativeName: "Português (Portugal)",
    dir: "ltr",
  },
  {
    code: "ro",
    name: "Romanian",
    nativeName: "Română",
    dir: "ltr",
  },
  {
    code: "ru",
    name: "Russian",
    nativeName: "Русский",
    dir: "ltr",
  },
  {
    code: "run",
    name: "Rundi",
    nativeName: "Rundi",
    dir: "ltr",
  },
  {
    code: "rw",
    name: "Kinyarwanda",
    nativeName: "Kinyarwanda",
    dir: "ltr",
  },
  {
    code: "sd",
    name: "Sindhi",
    nativeName: "سنڌي",
    dir: "ltr",
  },
  {
    code: "si",
    name: "Sinhala",
    nativeName: "සිංහල",
    dir: "ltr",
  },
  {
    code: "sk",
    name: "Slovak",
    nativeName: "Slovenčina",
    dir: "ltr",
  },
  {
    code: "sl",
    name: "Slovenian",
    nativeName: "Slovenščina",
    dir: "ltr",
  },
  {
    code: "sm",
    name: "Samoan",
    nativeName: "Gagana Sāmoa",
    dir: "ltr",
  },
  {
    code: "sn",
    name: "Shona",
    nativeName: "chiShona",
    dir: "ltr",
  },
  {
    code: "so",
    name: "Somali",
    nativeName: "Soomaali",
    dir: "ltr",
  },
  {
    code: "sq",
    name: "Albanian",
    nativeName: "Shqip",
    dir: "ltr",
  },
  {
    code: "sr-Cyrl",
    name: "Serbian (Cyrillic)",
    nativeName: "Српски (ћирилица)",
    dir: "ltr",
  },
  {
    code: "sr-Latn",
    name: "Serbian (Latin)",
    nativeName: "Srpski (latinica)",
    dir: "ltr",
  },
  {
    code: "sv",
    name: "Swedish",
    nativeName: "Svenska",
    dir: "ltr",
  },
  {
    code: "sw",
    name: "Swahili",
    nativeName: "Kiswahili",
    dir: "ltr",
  },
  {
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    dir: "ltr",
  },
  {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    dir: "ltr",
  },
  {
    code: "tg",
    name: "Tajik",
    nativeName: "Тоҷикӣ",
    dir: "ltr",
  },
  {
    code: "th",
    name: "Thai",
    nativeName: "ไทย",
    dir: "ltr",
  },
  {
    code: "ti",
    name: "Tigrinya",
    nativeName: "ትግርኛ",
    dir: "ltr",
  },
  {
    code: "tk",
    name: "Turkmen",
    nativeName: "Türkmençe",
    dir: "ltr",
  },
  {
    code: "tl",
    name: "Tagalog",
    nativeName: "Tagalog",
    dir: "ltr",
  },
  {
    code: "tn",
    name: "Tswana",
    nativeName: "Setswana",
    dir: "ltr",
  },
  {
    code: "to",
    name: "Tongan",
    nativeName: "Lea Faka-Tonga",
    dir: "ltr",
  },
  {
    code: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
    dir: "ltr",
  },
  {
    code: "tt",
    name: "Tatar",
    nativeName: "Татарча",
    dir: "ltr",
  },
  {
    code: "ug",
    name: "Uighur",
    nativeName: "ئۇيغۇرچە",
    dir: "ltr",
  },
  {
    code: "uk",
    name: "Ukrainian",
    nativeName: "Українська",
    dir: "ltr",
  },
  {
    code: "ur",
    name: "Urdu",
    nativeName: "اردو",
    dir: "rtl",
  },
  {
    code: "uz",
    name: "Uzbek",
    nativeName: "Oʻzbekcha",
    dir: "ltr",
  },
  {
    code: "vi",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    dir: "ltr",
  },
  {
    code: "yua",
    name: "Yucatec Maya",
    nativeName: "Yucatec Maya",
    dir: "ltr",
  },
  {
    code: "yue",
    name: "Cantonese (Traditional)",
    nativeName: "粵語 (繁體)",
    dir: "ltr",
  },
  {
    code: "zh-Hans",
    name: "Chinese (Simplified)",
    nativeName: "中文 (简体)",
    dir: "ltr",
  },
  {
    code: "zh-Hant",
    name: "Chinese (Traditional)",
    nativeName: "中文 (繁體)",
    dir: "ltr",
  },
  {
    code: "zu",
    name: "Zulu",
    nativeName: "isiZulu",
    dir: "ltr",
  },
];